/**
 * Watchlist workflow: generate the BizHawk watchlist from code notes, verify
 * it covers every address the achievements read, and refresh the labels
 * stored in existing scenarios. One conceptual action - "my notes changed" -
 * exposed as `cruncheevos-playtest watchlist <gameDir>`.
 *
 * Node-only.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import { parseCodeNotes, codeNotesToWatchlist } from './code-notes.js';
import { parseTrigger } from './engine/trigger.js';
import { memrefSharedSize } from './engine/memref.js';
import { findScenarioDirs } from './discover.js';

/** Locate the code notes file in a game folder. */
export function findNotesFile(gameDir) {
  const entries = readdirSync(gameDir);
  const byPreference = [
    (f) => f === 'notes.json',
    (f) => /-Notes\.json$/i.test(f),
    (f) => /-User\.txt$/i.test(f),
  ];
  for (const matches of byPreference) {
    const hit = entries.find(matches);
    if (hit) return join(gameDir, hit);
  }
  return null;
}

/** Serialize watchlist entries as the Lua module the recorder loads. */
export function watchlistLua(entries, sourceName) {
  const luaEscape = (s) => s.replace(/[\\"]/g, '\\$&');
  const lines = entries.map(({ address, size, label }) =>
    `    { address = 0x${address.toString(16).padStart(4, '0')}, size = "${size}", label = "${luaEscape(label ?? '')}" },`);
  return `-- generated by cruncheevos-playtest from ${sourceName}\nreturn {\n${lines.join('\n')}\n}\n`;
}

const SIZE_TO_WATCH = { '8bit': 'u8', '16bit': 'u16', '32bit': 'u32' };

/**
 * Cross-reference the addresses an achievement set reads against a set of
 * watched addresses. Returns [{ address, size, usedBy }] for uncovered ones.
 */
export function findUncoveredAddresses(setModule, watchedAddresses) {
  const needed = new Map();

  for (const achievement of Object.values(setModule.achievements)) {
    const definition = achievement.conditions
      .map((group) => group.map((c) => c.toString()).join('_')).join('S');
    const trigger = parseTrigger(definition);
    for (const memref of trigger.memrefs.memrefs) {
      const entry = needed.get(memref.address) ??
        { size: SIZE_TO_WATCH[memrefSharedSize(memref.size)] ?? 'u32', usedBy: new Set() };
      entry.usedBy.add(achievement.title);
      needed.set(memref.address, entry);
    }
  }

  return [...needed.entries()]
    .filter(([address]) => !watchedAddresses.has(address))
    .sort((a, b) => a[0] - b[0])
    .map(([address, { size, usedBy }]) => ({ address, size, usedBy: [...usedBy] }));
}

/**
 * Rewrite the address labels of every scenario under gameDir from the given
 * notes. Returns [{ dir, updated }].
 */
export function refreshScenarioLabels(gameDir, notes) {
  const labelByAddress = new Map(notes.map((n) => [n.address, n.label]));
  const results = [];

  for (const rel of findScenarioDirs(gameDir)) {
    const metaPath = join(gameDir, rel, 'meta.json');
    if (!existsSync(metaPath)) continue;

    const meta = JSON.parse(readFileSync(metaPath, 'utf8'));
    if (!Array.isArray(meta.addresses)) continue;

    let updated = 0;
    for (const entry of meta.addresses) {
      const label = labelByAddress.get(parseInt(entry.address, 16));
      if (label !== undefined && label !== entry.label) {
        entry.label = label;
        updated++;
      }
    }

    if (updated) writeFileSync(metaPath, JSON.stringify(meta, null, 2) + '\n');
    results.push({ dir: rel, updated });
  }

  return results;
}

export { parseCodeNotes, codeNotesToWatchlist };
